# Generated by Django 3.0.5 on 2020-05-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200511_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmationcode',
            old_name='confirmation_code',
            new_name='code',
        ),
    ]
