# Generated by Django 3.0.5 on 2020-04-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200427_1426"),
    ]

    operations = [
        migrations.RemoveField(model_name="title", name="genre",),
        migrations.AddField(
            model_name="title",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="genre",
                to="api.Genre",
            ),
        ),
    ]
