# Generated by Django 3.0.5 on 2020-04-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_title_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
